### ISSUE TITLE
Invoke-UiaButtonClick hanging

### ISSUE THREAD

**Issue by konstantinvlasenko** [apetrovskiy/STUPS#4]
Hi, we have an issue.
Get-UiaButton -Name 'Add...' | Invoke-UiaButtonClick
The line abode does make a job. So the button clicked and new dialog appears.
But the problem is that this line doesn't return a control. SO the whole script is hanging at this point.

PowerShell 4.0
Windows 2012 R2

**Comment by apetrovskiy** [comment]
Hello, the first thing I thought about is that there are more than one button with name 'Add...' in the form. The second cmdlet accepts two or more elements and click each of them. Probably, the dialog invoked prevents the cmdlet from clicking the next 'Add...' button and the cmdlet waits.

What does the statement Get-UiaButton -Name 'Add...' outputs?

**Comment by JiangYu1** [comment]
_(Get-UiaButton -Name 'Add...').Count_ returns **1**

**Comment by apetrovskiy** [comment]
What is logged? If you didn't set log path, the default location is that is set here: [UIAutomation.Preferences]::LogPath (by default, the log's called UIA.log and it's saved to My Documents).
Could you provide me with entries around getting the button, clicking it and getting a control the button is in (window, panel, etc)?

**Comment by JiangYu1** [comment]
Thanks!
Here are the cmdlets around it. I will find the log and attach it.
Get-UiaGroup -Name 'Auditing' | Invoke-UIAMenuItemClick
Get-UiaDataItem -Name 'SQL Data Level (0)' | Invoke-UIAMenuItemClick
**Get-UiaButton -Name 'Add...' | Invoke-UiaButtonClick**
## new window open after  clicking 'Add...', then hanging, the following code doesn't run
Get-UiaWindow -Name 'SQL Data Level Auditing Wizard'
Get-UiaEdit -AutomationId 'ultraTextTemplateName_EmbeddableTextBox' | Set-UiaEditText -Text 'MySqlDlaTemplate'
Get-UiaEdit -AutomationId 'ultraTextSqlServer' | Set-UiaEditText -Text 'SQL'

**Comment by JiangYu1** [comment]
sorry for bad formatting above, i selected wrong one

**Comment by JiangYu1** [comment]
Here is the log file.
[UIAlog.txt](https://github.com/apetrovskiy/STUPS/files/132747/UIAlog.txt)

Thanks!

**Comment by apetrovskiy** [comment]
As can I see, there is damn Infragistics. Those guys in early times didn't support automation excepting their own tools and probably this is the reason that UI Automation cannot recognize event that the button's underlaying code has finished.

I'd suggest using other cmdlet, for example, Invoke-UiaControlClick.
In basic case, the use of this cmdlet is easy as the Invoke-UiaButtonClick:
Start-Process calc -PassThru | Get-UiaWindow | Get-UiaButton 1 | Invoke-UiaControlClick

It works over Win32 API (not over MS UI Automation), so there are chances to automate the control. As can be seen, the button has handle (NativeWindowHandle="131754") and this cmdlet should be able to click into the button.

**Comment by JiangYu1** [comment]
Thanks for the reply!

I have a try with the cmdlet: Invoke-UiaControlClick. It is completed, but no new window is opened after clicking action. Then Get-UiaWindow failed.
...
Get-UiaDataItem -Name 'SQL Data Level (0)' | Invoke-UIAMenuItemClick
Get-UiaButton -Name 'Add...' | Invoke-UiaControlClick 
Get-UiaWindow -Name 'SQL Data Level Auditing Wizard'
...
[UIA.log.txt](https://github.com/apetrovskiy/STUPS/files/132981/UIA.log.txt)

Any suggestion about this?

**Comment by apetrovskiy** [comment]
This button is definitely refusing to work as a normal control, isn't it? Try, for example, one of the following:
Start-Process calc -PassThru | Get-UiaWindow
$button = Get-UiaButton 1
1) $button.Control.Click()
2) $button.Mouse.LeftButtonClick()
3) $button.Keyboard.KeyDown("RETURN") # or whatever short cut the button supports
Sometimes, a better way is to hit a control with a keyboard key, navigating to it by pressing Tab.

**Comment by JiangYu1** [comment]
This line "2) $button.Mouse.LeftButtonClick()" working for me! 

Thank you very much, save me a day!

**Comment by apetrovskiy** [comment]
The issue has been solved!
